### ISSUE TITLE
Automated tests and CI

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [EGaraldi/corecon#10]
Hello,

I noticed that you have some tests set up [here (Travis CI)](https://travis-ci.org/github/EGaraldi/corecon) which is great!

I think common errors would be things like
```
dimensions_descriptors = [ redshift ]
err_up2                = [ nan ]
```
when contributors create pull requests for new constraints -- yep, I just made those errors myself ;)

I'm not very familiar with Travis but from glancing at the config I think it does test the installation via `setup.py`. Does this catch these errors (`pip install -e` doesn't)? Otherwise I would suggest adding an `import corecon` to the test as this would catch such errors (finding undefined variables).

Best,
Stefan

**Comment by EGaraldi** [comment]
Nice catch. I have moved to github workflows (since in the meantime travisCI became paid-only) and now this is checked.
