### ISSUE TITLE
Referee (Fialkov) comments on the paper 

### ISSUE THREAD

**Issue by afialkov** [EGaraldi/corecon#3]
It is a very interesting idea and a useful initiative!

There are several improvements that I would like to suggest:

In the first paragraph, the author rightfully states that the data in the field have different formats, often appear in plots only and/or is not public. Extracting data from a plot, without having the data themselves, and using it for science is not the best scientific practice. Because CoReCon is envisioned as a community tool, it would be good to adopt the best practice from the start. In the paper Garaldi mentions that some of the data in the CoReCon database were indeed “from a published plot”. Would it be possible to contact authors and ask for the original data that went into the plots instead? If they are not willing to share, perhaps such data should not be included at all.

It would be useful to have some specific examples in the paper of data used, homogenisation of the data, inputs, outputs. The paper is lacking details on which constraints have already been implemented in the code. A list of constraints appears at the end of the paper, but there are no details and no references. Ideally, each item deserves a separate sentence/paragraph and a short description of what are the actual constraints that the code already provides. Also include which data were used, references, caveats (if any). If such a description exists (e.g., in the documentation) please give a reference. A table of all the implemented constraints with references and details would be extremely useful. If such a table exists, please add a reference. 

In general, references are lacking.

The listed constraints act on different aspects of the EoR. It would be good to give an overview of what aspects of physics each constraint tackles. How different constraints are related? 

Since this is supposed to be a public database, it would be useful to have a list of data that have not been included, but would be good to have ("future work"). So that different contributors could pitch in. 

“column density ratio” is mentioned but it is not clear column density of what. Please specify.

“star formation rate density” at what redshifts?

“correlation between the flux in Lyman-alpha spikes and galaxy position” – what does it say about the EoR?

I also found some typos in the paper: 
“ data layout” -> “data layouts”
“ internally transform”-> “ internally transforms”
“one of the two data format”-> “one of the two data formats”

Anastasia

**Comment by EGaraldi** [comment]
Dear Anastasia, 
please accept my apologies for the long silence. I had some personal issues in 2020 that forced me to focus away from this project. I then had to find a new job, and by the time this was done the JOSS submission was closed for inactivity, so I drifted away from this project. 
I have now finally restarted working on this project, so I want to honor your review work even though the submission is closed. I leave below my reply to your report. Of course, I do not expect a reply, but should you decide to do so, you can expect a (much much) quicker response from now on.

Best regards,
Enrico 


[referee_report_corecon.txt](https://github.com/EGaraldi/corecon/files/9200446/referee_report_corecon.txt)
