### ISSUE TITLE
Using names for fields instead of variable names ('IGM_temperature' instead of 'T0')

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [EGaraldi/corecon#7]
Hi again,

the currently supported fields are a mixture of variable names and words:
```
>>> crc.fields()
['ionized_fraction', 'Lya_flux_ps', 'mfp', 'tau_eff_HI', 'tau_eff_HeII', 'eta', 'qlf',
 'glf', 'T0', 'tau_cmb', 'sfrd', 'Lya_spike_galaxy_correlation']
```
Variables like `eta`, `qlf`, `glf`, `T0` are very hard to identify for people not familiar with the work. I had no idea what `eta` is without looking it up. Especially if this project is growing to include a large number of constraints, one can't look up every variable name so proper naming would be important.

I would suggest to rename to constraints to worlds (like `ionized_fraction`), e.g. rename `T0` to `IGM_temperature`. This also eliminates confusion from reused variable names (e.g. the CMB temperature is commonly referred to as `T0` too).

Cheers,
Stefan

**Comment by EGaraldi** [comment]
Hi,
I've implemented this.
